 <DoughnutChart
                count={all}
                legendDis={false}
                cutout={6}
                width={400}
                height={250}
                countPosY={-70}
                totalPosY={0}
                countPosX={0}
                totalPosX={10}
                chartConfig={data}
              />
